//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cms.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CMSEntities : DbContext
    {
        public CMSEntities()
            : base("name=CMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<daugia> daugias { get; set; }
        public virtual DbSet<editor> editors { get; set; }
        public virtual DbSet<gopy> gopies { get; set; }
        public virtual DbSet<member> members { get; set; }
        public virtual DbSet<menu> menus { get; set; }
        public virtual DbSet<module> modules { get; set; }
        public virtual DbSet<news_item> news_item { get; set; }
        public virtual DbSet<news_item_image> news_item_image { get; set; }
        public virtual DbSet<news_item_menu> news_item_menu { get; set; }
        public virtual DbSet<page> pages { get; set; }
        public virtual DbSet<pages_modules_pos> pages_modules_pos { get; set; }
        public virtual DbSet<saoke> saokes { get; set; }
        public virtual DbSet<donor> donors { get; set; }
        public virtual DbSet<web_link> web_link { get; set; }
        public virtual DbSet<project_cat> project_cat { get; set; }
        public virtual DbSet<province> provinces { get; set; }
        public virtual DbSet<projects_fund> projects_fund { get; set; }
    }
}
