//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class module
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<byte> is_news { get; set; }
        public Nullable<byte> is_album { get; set; }
        public Nullable<byte> is_list { get; set; }
        public Nullable<byte> is_poll { get; set; }
        public Nullable<byte> is_slide { get; set; }
        public Nullable<byte> is_contact { get; set; }
        public Nullable<int> type { get; set; }
    }
}
