//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class news_item
    {
        public int id { get; set; }
        public string title { get; set; }
        public string des { get; set; }
        public string full_content { get; set; }
        public string image { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> deleted { get; set; }
        public Nullable<System.DateTime> datetime { get; set; }
        public Nullable<int> datetimeid { get; set; }
        public Nullable<int> total_views { get; set; }
        public string user_post { get; set; }
        public Nullable<int> menu_id { get; set; }
        public Nullable<System.DateTime> date_time_dau_gia { get; set; }
    }
}
