//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pages_modules_pos
    {
        public int id { get; set; }
        public Nullable<int> pages_id { get; set; }
        public Nullable<int> modules_id { get; set; }
        public Nullable<byte> pos { get; set; }
        public Nullable<int> order_no { get; set; }
    }
}
