//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class projects_fund
    {
        public int id { get; set; }
        public string name { get; set; }
        public string des { get; set; }
        public Nullable<decimal> money1 { get; set; }
        public Nullable<decimal> money2 { get; set; }
        public string img { get; set; }
        public Nullable<System.DateTime> date_init { get; set; }
        public Nullable<int> project_cat { get; set; }
        public string orderby { get; set; }
        public string provinces { get; set; }
        public Nullable<long> authorid { get; set; }
        public string info { get; set; }
        public string des_detail { get; set; }
        public Nullable<int> view_count { get; set; }
        public Nullable<System.DateTime> date_finish { get; set; }
    }
}
